test('name of test', () => {
    //code to test node app
    //if this code throws error then it is a failure, ohterwise it good to go
})


test('failure test case', () => {
    // throw new Error('this is an error')  
})